# Generated by Django 5.2.3 on 2025-06-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('post_nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=128, null=True)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1)),
                ('profession', models.CharField(blank=True, max_length=250, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_nais', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('biographie', models.TextField(blank=True, null=True)),
                ('image_profil', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1)),
                ('dernier_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
