# Generated by Django 5.2.3 on 2025-06-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='dernier_login',
        ),
    ]
