# Generated by Django 5.2.3 on 2025-07-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usercompte', '0002_alter_blog_image_alter_imagehistorique_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type_fichier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
