# Generated by Django 5.2.3 on 2025-06-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0002_remove_profil_dernier_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
