# Generated by Django 5.2.3 on 2025-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usercompte', '0003_message_type_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notifie',
            field=models.BooleanField(default=False),
        ),
    ]
