# Generated by Django 5.2.3 on 2025-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0003_profil_derniere_connexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='App_UserCompte.profil'),
        ),
    ]
