# Generated by Django 5.2.3 on 2025-07-03 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usercompte', '0004_message_notifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='derniere_activité',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
