# Generated by Django 5.2.3 on 2025-06-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0008_probleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
