# Generated by Django 5.2.3 on 2025-06-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0011_alter_blog_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='statut',
            field=models.CharField(choices=[('1', 'Publié'), ('0', 'Brouillon')], default='0', max_length=10),
        ),
    ]
