# Generated by Django 5.2.3 on 2025-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0012_alter_blog_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='statut',
            field=models.CharField(choices=[('publié', 'Publié'), ('brouillon', 'Brouillon')], default='brouillon', max_length=10),
        ),
    ]
