# Generated by Django 5.2.3 on 2025-06-18 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0015_blog_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('commentaire', 'Commentaire'), ('signalement', 'Signalement'), ('modification', 'Modification')], max_length=50)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='App_UserCompte.profil')),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_envoyees', to='App_UserCompte.profil')),
            ],
        ),
    ]
