# Generated by Django 5.2.3 on 2025-06-19 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='emetteur',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_emises', to='App_UserCompte.profil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
