# Generated by Django 5.2.3 on 2025-06-19 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0017_alter_notification_emetteur_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPublier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier_video', models.FileField(upload_to='videos/')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='video_covers/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='App_UserCompte.profil')),
                ('likes', models.ManyToManyField(blank=True, related_name='videos_aimees', to='App_UserCompte.profil')),
            ],
        ),
    ]
