# Generated by Django 5.2.3 on 2025-06-19 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0018_videopublier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_UserCompte.profil')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='App_UserCompte.videopublier')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
