# Generated by Django 5.2.3 on 2025-06-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0019_commentairevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopublier',
            name='image_couverture',
        ),
    ]
