# Generated by Django 5.2.3 on 2025-06-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0020_remove_videopublier_image_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopublier',
            name='vus_par',
            field=models.ManyToManyField(blank=True, related_name='videos_vues', to='App_UserCompte.profil'),
        ),
    ]
