# Generated by Django 5.2.3 on 2025-06-22 18:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0021_videopublier_vus_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationAmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='envoyee', max_length=20)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to='App_UserCompte.profil')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to='App_UserCompte.profil')),
            ],
            options={
                'unique_together': {('emetteur', 'recepteur')},
            },
        ),
        migrations.CreateModel(
            name='RelationAmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_relation', models.DateTimeField(default=django.utils.timezone.now)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ami_1', to='App_UserCompte.profil')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ami_2', to='App_UserCompte.profil')),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
