# Generated by Django 5.2.3 on 2025-06-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0024_message_lu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='lu',
        ),
    ]
