# Generated by Django 5.2.3 on 2025-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0026_message_lu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='chat_fichiers/'),
        ),
    ]
