# Generated by Django 5.2.3 on 2025-06-26 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0027_alter_message_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='historique_profils/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_historiques', to='App_UserCompte.profil')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
