# Generated by Django 5.2.3 on 2025-06-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0028_imagehistorique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='stories/')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_UserCompte.profil')),
            ],
        ),
    ]
