# Generated by Django 5.2.3 on 2025-06-26 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0029_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='media',
        ),
        migrations.RemoveField(
            model_name='story',
            name='type_media',
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/images/'),
        ),
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories/videos/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='expire_le',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 20, 28, 56, 609303, tzinfo=datetime.timezone.utc)),
        ),
    ]
