# Generated by Django 5.2.3 on 2025-06-26 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0030_remove_story_media_remove_story_type_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expire_le',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 21, 12, 51, 747725, tzinfo=datetime.timezone.utc)),
        ),
    ]
