# Generated by Django 5.2.3 on 2025-06-27 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0031_alter_story_expire_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='story_likes', to='App_UserCompte.profil'),
        ),
        migrations.AlterField(
            model_name='story',
            name='expire_le',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 8, 43, 24, 712891, tzinfo=datetime.timezone.utc)),
        ),
    ]
