# Generated by Django 5.2.3 on 2025-06-27 17:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0032_story_likes_alter_story_expire_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expire_le',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 17, 58, 38, 364189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='App_UserCompte.profil')),
            ],
        ),
    ]
