# Generated by Django 5.2.3 on 2025-06-27 21:21

import App_UserCompte.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserCompte', '0033_alter_story_expire_le_messageia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expire_le',
            field=models.DateTimeField(default=App_UserCompte.models.get_expiration_date),
        ),
    ]
